version: "3.9"
services:
  db:
    image: postgres:15
    container_name: quizbank_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizbank
    volumes:
      - db_data:/var/lib/postgresql/data      # persistent data volume
      # - ./db-init:/docker-entrypoint-initdb.d # only for first init
    ports:
      - "5432:5432"

volumes:
  db_data:
