version: "3.8"

services:
  db:
    image: postgres:18
    container_name: quizbank-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizbank
    ports:
      - "5433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - quizbank_data:/var/lib/postgresql/data

  web:                              # ADD THIS WHOLE SECTION
    build: .
    container_name: quizbank-api
    restart: always
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quizbank
    depends_on:
      - db
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    command: bash -c "python load_sample_data.py && python app.py"

volumes:
  quizbank_data: