"""init tables

Revision ID: e926b10756ca
Revises: 
Create Date: 2025-09-22 11:47:11.187394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e926b10756ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_table('performance')
    op.drop_table('question_usage')
    op.drop_table('question_versions')
    op.drop_table('assessment_questions')
    op.drop_table('questions')
    op.drop_table('question_tags')
    op.drop_table('tags')
    op.drop_table('assessments')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'instructor'::character varying"))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=25),
               nullable=True,
               existing_server_default=sa.text("'instructor'::character varying"))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.create_table('assessments',
    sa.Column('assessment_id', sa.INTEGER(), server_default=sa.text("nextval('assessments_assessment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('assessment_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='assessments_course_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='assessments_created_by_fkey'),
    sa.PrimaryKeyConstraint('assessment_id', name='assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.INTEGER(), server_default=sa.text("nextval('tags_tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tag_id', name='tags_pkey'),
    sa.UniqueConstraint('tag_name', name='tags_tag_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('question_tags',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('question_tags_question_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], name=op.f('question_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('question_id', 'tag_id', name=op.f('question_tags_pkey'))
    )
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), server_default=sa.text("nextval('questions_question_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difficulty_index', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='questions_course_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='questions_created_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name='questions_updated_by_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_questions_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('assessment_questions_question_id_fkey')),
    sa.PrimaryKeyConstraint('assessment_id', 'question_id', name=op.f('assessment_questions_pkey'))
    )
    op.create_table('question_versions',
    sa.Column('version_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('question_versions_question_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('question_versions_updated_by_fkey')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('question_versions_pkey'))
    )
    op.create_table('question_usage',
    sa.Column('usage_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('question_usage_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('question_usage_question_id_fkey')),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('question_usage_pkey'))
    )
    op.create_table('performance',
    sa.Column('performance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discriminant_index', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('performance_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('performance_question_id_fkey')),
    sa.PrimaryKeyConstraint('performance_id', name=op.f('performance_pkey'))
    )
    op.create_table('datasets',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('datasets_question_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name=op.f('datasets_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('dataset_id', name=op.f('datasets_pkey'))
    )
    # ### end Alembic commands ###
